Nomdusite/app/src/Entity/Destination.php
<?php

namespace App\Entity;

use App\Repository\DestinationRepository;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: DestinationRepository::class)]
#[ApiResource(
    normalizationContext: ['groups' => ['dest:read']],
    denormalizationContext: ['groups' => ['dest:write']]
)]
class Destination
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['dest:read', 'dest:write'])]
    private ?string $label = null;

    #[ORM\Column(length: 255)]
    #[Groups(['dest:read'])]
    private ?string $image_path = null;

    #[ORM\Column(length: 255)]
    private ?string $drapeau = null;

    #[ORM\Column(length: 255)]
    private ?string $visa = null;

    #[ORM\Column(length: 255)]
    private ?string $passport = null;

    #[ORM\Column(length: 255)]
    private ?string $secure = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $langue = null;

    #[ORM\Column(length: 255)]
    private ?string $monnaie = null;

    #[ORM\Column(length: 255)]
    private ?string $debut_saison = null;

    #[ORM\Column(length: 255)]
    private ?string $fin_saison = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): static
    {
        $this->label = $label;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function getDrapeau(): ?string
    {
        return $this->drapeau;
    }

    public function setDrapeau(string $drapeau): static
    {
        $this->drapeau = $drapeau;

        return $this;
    }

    public function getVisa(): ?string
    {
        return $this->visa;
    }

    public function setVisa(string $visa): static
    {
        $this->visa = $visa;

        return $this;
    }

    public function getPassport(): ?string
    {
        return $this->passport;
    }

    public function setPassport(string $passport): static
    {
        $this->passport = $passport;

        return $this;
    }

    public function getSecure(): ?string
    {
        return $this->secure;
    }

    public function setSecure(string $secure): static
    {
        $this->secure = $secure;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLangue(): ?string
    {
        return $this->langue;
    }

    public function setLangue(string $langue): static
    {
        $this->langue = $langue;

        return $this;
    }

    public function getMonnaie(): ?string
    {
        return $this->monnaie;
    }

    public function setMonnaie(string $monnaie): static
    {
        $this->monnaie = $monnaie;

        return $this;
    }

    public function getDebutSaison(): ?string
    {
        return $this->debut_saison;
    }

    public function setDebutSaison(string $debut_saison): static
    {
        $this->debut_saison = $debut_saison;

        return $this;
    }

    public function getFinSaison(): ?string
    {
        return $this->fin_saison;
    }

    public function setFinSaison(string $fin_saison): static
    {
        $this->fin_saison = $fin_saison;

        return $this;
    }
}

Nomdusite/app/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Destination;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

# On crée une classe HomeController qui hérite de AbstractController

class HomeController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    
    #[Route('/', name: 'home_')]
    public function index()
    {
        return $this->render('home/index.html.twig');
    }

    #[Route('/continents', name: 'continents')]
    public function continents()

    {

        $ps = $this->entityManager->getRepository(Destination::class)->findAll();

        return $this->render('home/map.html.twig',
        [
            'ps' => $ps
        ]);
    } 

    
    #[Route('/modejoueursolo', name:'md_joueur')]
    public function modejoueur()
    {
        return $this->render('home/modesolo/acceuil.html.twig');
    }
    #[Route('/pays', name:'pays')]
    public function pays()
    {
        return $this->render('home/pays/detailpays.html.twig');
    }
}

Nomdusite/app/templates/home/continents.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tout les continents{% endblock %}

{% block body %}
{{ include ('home/_parts/_navbar.html.twig') }}

<body>
{# liste des pays #}
<div class="container mt-5">
    <h2 class="text-center">Toutes les destinations</h2>  
    <div class="row">
        <div class="col-md-4">
        {% for ps in ps %}
            <div class="card">
                <img src="/upload/images/pays/{{ ps.imagePath }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ ps.label }}</h5>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, voluptate.</p>
                    <a href="{{ path ('detailpays', {'id': ps.id}) }}" class="btn btn-primary">Voir plus</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}





<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="https://unpkg.com/leaflet-geoman-free/dist/leaflet-geoman.min.js"></script>
<script src="https://unpkg.com/leaflet-geoman-free/dist/leaflet-geoman.min.css"></script>
<script>
// Créer une carte centrée sur les coordonnées [0, 0] (l'équateur)
</script>



{% endblock %}

Nomdusite/app/templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
{{ include ('home/_parts/_navbar.html.twig') }}

     <div class="hero animate__animated animate__fadeIn">
        <h1 class="animate__animated animate__bounceInDown">Découvrez le Monde</h1>
        <p class="animate__animated animate__fadeInUp">Apprenez tout sur vos destinations de voyage préférées</p>
        <a href="{{ path ('continents') }}" class="btn btn-primary btn-lg animate__animated animate__zoomIn">Découvrez-le</a>
    </div>

<div class="section_solo">
<h1>Apprenez en jouant</h1>
<p>Quizz sur les destinations, par pays, ou dans le monde entier</p>
<a href="{{path ('md_joueur')}}" class="btn btn-primary btn-lg">Jouer maintenant</a>
</div>
{% endblock %}

Nomdusite/app/templates/home/map.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}

{{ include ('home/_parts/_navbar.html.twig') }}

<div id="map"style="height: 500px;">
</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jvectormap/2.0.5/jquery-jvectormap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jvectormap/2.0.5/jquery-jvectormap-world-mill-en.js"></script>
    <script>
       var map = L.map('map').setView([0, 0], 2);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
fetch('https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json')
    .then(response => response.json())
    .then(data => {
        L.geoJSON(data, {
            onEachFeature: function(feature, layer) {
                layer.on('click', function() {
                    window.location.href = '/pays/' + feature.properties.iso_a2;
                });
            }
        }).addTo(map);
    });

    </script>

</script>
{% endblock %}